"""
Captures a real run into docs/ so a judge can see results without cloning.

Everything under docs/ is generated by this script from an actual run. Nothing
is hand-edited, which is the point: if a figure in docs/ disagrees with the
code, this script is what proves it.

    python docs/capture_sample_run.py

Run it with OPENAI_API_KEY set to capture the full three-tier pipeline, or
without to capture the degraded configuration. The header of the generated
transcript records which one it was.
"""

import contextlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

try:
    from dotenv import load_dotenv

    load_dotenv(Path(__file__).resolve().parent.parent / ".env")
except ImportError:
    pass

from src.evaluate import print_evaluation, run_evaluation  # noqa: E402
from src.report import print_summary  # noqa: E402

DOCS = Path(__file__).resolve().parent
ROOT = DOCS.parent
AUDIT_SAMPLE_LINES = 25


def capture(data_dir, output_dir):
    """Runs the pipeline and returns (printed text, report, evaluation)."""
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        payload, result, ablation = run_evaluation(data_dir=data_dir,
                                                   output_dir=output_dir)
        report = json.loads(Path(output_dir, "reconciliation_report.json").read_text())
        print_summary(report)
        print()
        print_evaluation(result, ablation)
    return buffer.getvalue(), report, payload


def sample_audit(path):
    """
    A representative slice, not the first N lines. Consecutive entries tend to
    be near-identical, so this takes a spread across stages and decisions so the
    file actually shows what the trail records: matches, each kind of exception,
    and the link proposals the later tiers make.

    Because the entries are non-consecutive, the excerpt deliberately does NOT
    verify as a hash chain -- verify_chain() reports a gap at the first skip,
    which is precisely the behaviour that makes the real trail worth having. The
    docs table says so, so nobody reads a sampled file as a broken audit trail.
    """
    entries = [json.loads(line) for line in
               path.read_text().strip().splitlines() if line.strip()]
    if not entries:
        return ""

    # The trail is append-only and long-lived, so it can hold entries written
    # before run_id existed. Sample only the newest run, defensively.
    latest = entries[-1].get("run_id")
    entries = [e for e in entries if e.get("run_id") == latest]

    seen = set()
    picked = []
    for entry in entries:
        # Group by the *shape* of the decision, not its text. Every basis
        # carries amounts and ids, so keying on the raw string would treat
        # every entry as unique and defeat the point of sampling.
        shape = re.sub(r"[0-9]+(?:\.[0-9]+)?", "N", entry["basis"])
        key = (entry["stage"], entry["decision"], shape[:60])
        if key in seen:
            continue
        seen.add(key)
        picked.append(entry)
        if len(picked) >= AUDIT_SAMPLE_LINES:
            break

    picked.sort(key=lambda e: e["timestamp"])
    return "\n".join(json.dumps(e) for e in picked)


def main():
    has_key = bool(os.environ.get("OPENAI_API_KEY"))
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Capture into a scratch directory so the sample reflects exactly one run
    # and never depends on, or writes to, whatever has accumulated in output/.
    scratch = Path(tempfile.mkdtemp(prefix="recon-docs-"))
    work = scratch / "primary"
    alt_work = scratch / "alt"
    work.mkdir()
    alt_work.mkdir()

    primary_text, primary_report, primary_eval = capture("data", str(work))
    alt_text, alt_report, _ = capture("data/alt", str(alt_work))

    tiers = primary_report["narration_resolution"]
    config = ("full pipeline, all three narration tiers"
              if has_key else
              "OPENAI_API_KEY not set, deterministic tiers only")

    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                            capture_output=True, text=True, cwd=ROOT)
    commit_id = commit.stdout.strip() or "unknown"

    transcript = f"""# Sample run

Generated by `python docs/capture_sample_run.py` at {stamp}, commit `{commit_id}`.
Nothing here is hand-edited.

**Configuration:** {config}. The LLM tier resolved {tiers['resolved_by_llm']} narration(s) and made {primary_report['throughput']['llm_calls']} API call(s) on this run.

---

## `python main.py --evaluate`

The primary 55-order batch.

```
{primary_text.strip()}
```

---

## `python main.py --alt --evaluate`

The same code against a batch using an entirely different bank's conventions:
`RRN`/`IMPS`/`AXIS` references with no `UTR` prefix anywhere, a
flat-plus-percentage fee model, T+1 settlement cadence, unfamiliar narration
templates. No line of `src/` changes to run it.

```
{alt_text.strip()}
```

---

## Files in this directory

| File | What it is |
|---|---|
| `sample-run.md` | this transcript |
| `reconciliation_report.json` | the full report from the primary run |
| `evaluation.json` | ground-truth scoring and the tier ablation |
| `audit_trail_sample.jsonl` | a representative spread of decisions, one per distinct stage/verdict shape. **An excerpt, so it does not verify as a hash chain** — non-consecutive entries are exactly what `verify_chain` is built to reject. The full trail it was sampled from does verify, which is what `audit_trail_intact` reports above |
| `capture_sample_run.py` | the script that generated all of the above |
| `benchmark.py` | regenerates the throughput table in the README; seeded, so every column but the timings reproduces exactly |
"""

    (DOCS / "sample-run.md").write_text(transcript)
    shutil.copy(work / "reconciliation_report.json", DOCS / "reconciliation_report.json")
    shutil.copy(work / "evaluation.json", DOCS / "evaluation.json")

    (DOCS / "audit_trail_sample.jsonl").write_text(
        sample_audit(work / "audit_trail.jsonl") + "\n")

    shutil.rmtree(scratch, ignore_errors=True)

    print(f"docs/ updated from a real run ({config})")
    print(f"  primary match rate: {primary_report['match_rate_pct']}%")
    print(f"  alt-format match rate: {alt_report['match_rate_pct']}%")
    print(f"  transcript: {len(transcript.splitlines())} lines")


if __name__ == "__main__":
    main()
